name: Build and Commit Webpack Output

on:
  push:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest  # your webpack config uses Windows-style paths

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # get full history so we can commit back

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        shell: pwsh
        run: |
          if (Test-Path package-lock.json) { npm ci } else { npm install }

      - name: Run webpack build
        run: npm run build

      - name: Commit build output
        uses: EndBug/add-and-commit@v9
        with:
          add: "src/client/public"
          message: "chore: build output [skip ci]"
          default_author: github_actions
