name: Build (webpack 5) and commit to root

on:
  push:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'github-actions[bot]' }}

    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - uses: actions/setup-node@v4
        with: { node-version: 20 }

      - name: Clean lockfile (optional safety if old lock exists)
        run: |
          if [ -f package-lock.json ]; then rm package-lock.json; fi

      - run: npm ci
      - run: npm run build

      # Copy dist/* to repo root so index.html + bundle.js are served by Pages
      - name: Copy build to root
        run: |
          cp -f dist/index.html index.html
          cp -f dist/bundle.js bundle.js

      - name: Commit built assets
        uses: EndBug/add-and-commit@v9
        with:
          add: |
            index.html
            bundle.js
            package-lock.json
          message: "build: webpack5 → root [skip ci]"
          default_author: github_actions
